// *****************************************************************************
// Module..: SDK -- Software development kit for Leddar products.
//
/// \file    RecordSettingsForm.cs
///
/// \brief   Form part of the LeddarNET example program to configure settings
///          for data recording.
///
// Platform: .NET
//
// Copyright (c) 2013 LeddarTech Inc. All rights reserved.
// Information contained herein is or may be confidential and proprietary to
// LeddarTech inc. Prior to using any part of the software development kit
// accompanying this notice, you must accept and agree to be bound to the
// terms of the LeddarTech Inc. license agreement accompanying this file.
// *****************************************************************************

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Text;
using System.Windows.Forms;

namespace LeddarNetDemo
{
    public partial class RecordSettingsForm : Form
    {
        private LeddarNET.Device mDevice;

        // *********************************************************************
        // Function: RecordSettingsForm
        //
        /// \brief   Constructor generated by form designer.
        // **********************************************************************

        public RecordSettingsForm()
        {
            InitializeComponent();
        }

        // *********************************************************************
        // Function: PBBrowseClick
        //
        /// \brief   Event-handler called when the Browse button is clicked.
        /// 
        /// A folder browser dialog is opened to allow the user to select a
        /// directory where record file will be saved. If the user does not
        /// cancel, the selected path is written in the textbox.
        /// 
        /// \param   sender  Not used
        /// \param   e       Not used
        // **********************************************************************

        private void
        PBBrowseClick( object sender, EventArgs e )
        {
            FolderBrowserDialog lDialog = new FolderBrowserDialog();

            if ( lDialog.ShowDialog( this ) == System.Windows.Forms.DialogResult.OK )
            {
                fTBDirectory.Text = lDialog.SelectedPath;
            }
        }

        // *********************************************************************
        // Function: PBOKClick
        //
        /// \brief   Event-handler called when the OK button is clicked.
        /// 
        /// Write the values from the control and close the form.
        /// 
        /// \param   sender  Not used
        /// \param   e       Not used
        // **********************************************************************

        private void
        PBOKClick( object sender, EventArgs e )
        {
            mDevice.ConfigureRecording( fTBDirectory.Text,
                                        (uint)fNUDSize.Value, 0 );
            Close();
        }

        // *********************************************************************
        // Function: TheDevice
        //
        /// \brief   Property to pass the device to work with.
        // **********************************************************************

        public LeddarNET.Device TheDevice
        {
            get
            {
                return mDevice;
            }
            set
            {
                mDevice = value;
                fTBDirectory.Text = mDevice.RecordingDirectory;
                fNUDSize.Value = mDevice.MaxRecordFileSize;
            }
        }
    }
}

// End of file RecordSettingsForm.cs
